export const notesRoutes = [
    {
        path: "/notes/engineeringmaths1",
        pageTitle: "Engineering Mathematics - I | NITKeChhore",
        heading: "Engineering Mathematics - I",
        subject: "Mathematics",
        loadingText: "Loading mathematics notes...",
        emptyTitle: "No Mathematics Notes Yet",
        emptyMessage: "Mathematics notes haven't been uploaded yet. Check back later for new notes.",
        semester: 1,
    },
    {
        path: "/notes/engineeringmaths2",
        pageTitle: "Engineering Mathematics - II | NITKeChhore",
        heading: "Engineering Mathematics - II",
        subject: "Mathematics",
        loadingText: "Loading mathematics notes...",
        emptyTitle: "No Mathematics Notes Yet",
        emptyMessage: "Mathematics notes haven't been uploaded yet. Check back later for new notes.",
        semester: 2,
    },
    {
        path: "/notes/engineeringphy1",
        pageTitle: "Engineering Physics - I | NITKeChhore",
        heading: "Engineering Physics - I",
        subject: "Physics",
        loadingText: "Loading physics notes...",
        emptyTitle: "No Physics Notes Yet",
        emptyMessage: "Physics notes haven't been uploaded yet. Check back later for new notes.",
        semester: 1,
    },
    {
        path: "/notes/engineeringphy2",
        pageTitle: "Engineering Physics - II | NITKeChhore",
        heading: "Engineering Physics - II",
        subject: "Physics",
        loadingText: "Loading physics notes...",
        emptyTitle: "No Physics Notes Yet",
        emptyMessage: "Physics notes haven't been uploaded yet. Check back later for new notes.",
        semester: 2,
    },
    {
        path: "/notes/engineeringchem1",
        pageTitle: "Engineering Chemistry - I | NITKeChhore",
        heading: "Engineering Chemistry - I",
        subject: "Chemistry",
        loadingText: "Loading Chemistry notes...",
        emptyTitle: "No Chemistry Notes Yet",
        emptyMessage: "Chemistry notes haven't been uploaded yet. Check back later for new notes.",
        semester: 1,
    },
    {
        path: "/notes/engineeringchem2",
        pageTitle: "Engineering Chemistry - II | NITKeChhore",
        heading: "Engineering Chemistry - II",
        subject: "Chemistry",
        loadingText: "Loading Chemistry notes...",
        emptyTitle: "No Chemistry Notes Yet",
        emptyMessage: "Chemistry notes haven't been uploaded yet. Check back later for new notes.",
        semester: 2,
    },
    {
        path: "/notes/english",
        pageTitle: "English | NITKeChhore",
        heading: "Professional Communication in English",
        subject: "English",
        loadingText: "Loading English notes...",
        emptyTitle: "No English Notes Yet",
        emptyMessage: "English notes haven't been uploaded yet. Check back later for new notes.",
        semester: 1,
    },
    {
        path: "/notes/bee",
        pageTitle: "Basic Electrical Engineering | NITKeChhore",
        heading: "Basic Electrical Engineering",
        subject: "BEE",
        loadingText: "Loading BEE notes...",
        emptyTitle: "No BEE Notes Yet",
        emptyMessage: "BEE notes haven't been uploaded yet. Check back later for new notes.",
        semester: 1,
    },
    {
        path: "/notes/mechanics",
        pageTitle: "Engineering Mechanics | NITKeChhore",
        heading: "Engineering Mechanics",
        subject: "Mechanics",
        loadingText: "Loading Mechanics notes...",
        emptyTitle: "No Mechanics Notes Yet",
        emptyMessage: "Mechanics notes haven't been uploaded yet. Check back later for new notes.",
        semester: 1,
    },
    {
        path: "/notes/ip",
        pageTitle: "Introduction to Programming | NITKeChhore",
        heading: "Introduction to Programming",
        subject: "IP",
        loadingText: "Loading IP notes...",
        emptyTitle: "No IP Notes Yet",
        emptyMessage: "IP notes haven't been uploaded yet. Check back later for new notes.",
        semester: 1,
    },
    {
        path: "/notes/dstm",
        pageTitle: "Disaster Management | NITKeChhore",
        heading: "Disaster Management",
        subject: "DSTM",
        loadingText: "Loading DSTM notes...",
        emptyTitle: "No DSTM Notes Yet",
        emptyMessage: "DSTM notes haven't been uploaded yet. Check back later for new notes.",
        semester: 1,
    },
    {
        path: "/notes/be",
        pageTitle: "Basic Electronics | NITKeChhore",
        heading: "Basic Electronics",
        subject: "BE",
        loadingText: "Loading BE notes...",
        emptyTitle: "No BE Notes Yet",
        emptyMessage: "BE notes haven't been uploaded yet. Check back later for new notes.",
        semester: 1,
    },
];

export default notesRoutes;